version: "3"
services:
  # API Service
  api:
    build: .docker/php
    volumes:
      - ./api:/var/www
    depends_on:
      - db

  # Database(MySQL) Service
  db:
    image: mysql:5.7.29
    restart: always
    command: --innodb-use-native-aio=0
    ports:
      - ${DB_PORT}:3306
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  # Nginx Service
  webserver:
    build: .docker/nginx
    restart: always
    ports:
      - ${API_PORT}:80
    volumes:
      - ./api:/var/www
    depends_on:
      - api
